highlighter: rouge
permalink: pretty
markdown: kramdown

title: Fortran Programming Language
description: "Fortran Programming Language"
canonical_url: 'https://fortran-lang.org'

news:
    name: Fortran Newsletter
    authors: Fortran Community
    url: /news
    feed: /news.xml

plugins:

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor/
    
baseurl: /fortran-lang.org
